import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useState } from 'react'
import Card from '../components/Card'
import Modal from '../components/Modal'
import ModalText from '../components/ModalText'
import styles from '../styles/Home.module.css'
import bg from "../public/pacman-type.png"
import Link from 'next/link'

const Home = () => {
    const router = useRouter();

    const cards = [
      {
        title: "Card 1",
        text: "Received shutters expenses ye he pleasant. Drift as blind above at up. No up simple county stairs do should praise as. Drawings sir gay together landlord had law smallest. Formerly welcomed attended declared met say unlocked. Jennings outlived no dwelling denoting in peculiar as he believed. Behaviour excellent middleton be as it curiosity departure ourselves."
      },
      {
        title: "Card 2",
        text: "Lorem ipsum dolor sit amet. Et eveniet numquam non iure natus rem mollitia eius ad perspiciatis quis ab numquam voluptatem. Eos quia incidunt sed quas ullam qui fuga sint sit nihil quisquam! Quo nobis incidunt aut suscipit neque est esse molestias ea neque sunt hic obcaecati galisum ut galisum sint? Est voluptatem libero est ipsa iste aut quaerat deserunt in nemo recusandae! Quo galisum voluptas qui repellat similique ad amet cupiditate cum quis ullam est enim repellendus. Sed inventore velit est labore quaerat ut harum dolor ut nesciunt doloribus et officiis doloribus eos eveniet dolorem et natus blanditiis. Aut neque molestiae sit galisum reprehenderit ut obcaecati maiores est animi error qui voluptatem totam ut possimus sunt."
      },
      {
        title: "Card 3",
        text: "Article nor prepare chicken you him now. Shy merits say advice ten before lovers innate add. She cordially behaviour can attempted estimable. Trees delay fancy noise manor do as an small. Felicity now law securing breeding likewise extended and. Roused either who favour why ham."
      },
      {
        title: "Card 4",
        text: "Meant balls it if up doubt small purse. Required his you put the outlived answered position. An pleasure exertion if believed provided to. All led out world these music while asked. Paid mind even sons does he door no. Attended overcame repeated it is perceive marianne in. In am think on style child of. Servants moreover in sensible he it ye possible."
      },
    ]

    return (
      <>
        <Head>
          <title>Next.js Modals</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main} style={{
          backgroundImage: `url(${bg.src})`,
          backgroundRepeat: 'no-repeat',
          backgroundSize: '100% 100%',
        }}>
          <h1 className={styles.title}>Next.js Modals</h1>
          <div className={styles.box}>
            {cards.map(card => {
              const idx = cards.indexOf(card);
              return (
                <Link href={`?card=${idx}`}>
                  <Card key={idx} title={card["title"]} text={card["text"]} />
                </Link>
              );
            })}
          </div>
          {router.query.card && (
            <Modal close={() => router.push("/")}>
              <ModalText title={cards[router.query.card]["title"]} text={cards[router.query.card]["text"]} />
            </Modal>
          )}
        </main>
      </>
    )
}

export default Home;
